name: Publish Extension to NuGet.org

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Add package sources
      run: |
        dotnet nuget add source https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-Labs/nuget/v3/index.json -n CommunityToolkit-Labs

    - name: Restore dependencies
      run: dotnet restore src/WindowSill.WebBrowser/WindowSill.WebBrowser.csproj

    - name: Build project with MSBuild
      run: msbuild src/WindowSill.WebBrowser/WindowSill.WebBrowser.csproj /p:Configuration=Release /p:Platform="Any CPU" /p:RestorePackages=false

    - name: Create NuGet package with MSBuild
      run: msbuild src/WindowSill.WebBrowser/WindowSill.WebBrowser.csproj /t:Pack /p:Configuration=Release /p:Platform="Any CPU" /p:PackageOutputPath=${{ github.workspace }}/artifacts /p:NoBuild=true

    - name: Publish to NuGet.org
      run: dotnet nuget push "${{ github.workspace }}\artifacts\*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package
        path: ${{ github.workspace }}/artifacts/*.nupkg